### ISSUE TITLE
Switch var to let or const

### ISSUE THREAD

**Issue by c3ho** [Niaz-Ul-Haque/nlinks#1]
https://github.com/Niaz-Ul-Haque/nlinks/blob/adff79502af6a717ba978ebd69f09b5a06447cda/src/cli.js#L43

In the rest of the code you have either `const` or `let` why did you decide to use `var` here?

**Comment by Niaz-Ul-Haque** [comment]
Ohhhhh I see, I planned on changing that but I forgot midway haha. thanks for pointing it out. I copied var from an old variable I had in release 0.1, I planned on changing it.
