### ISSUE TITLE
vscode folder

### ISSUE THREAD

**Issue by joelazwar** [Niaz-Ul-Haque/nlinks#10]
Not a huge problem but I noticed you have your vscode folder up on the repo. I'm not sure it's necessary to have up on there.

**Comment by joelazwar** [comment]
I noticed cause my vscode pimped itself out when i cloned the repo locally hahahah

**Comment by Niaz-Ul-Haque** [comment]
oohhh, I see. That is because I am using a custom theme for my vs, unfortunately, it got added here. I'll make sure to put this folder under my gitignore in the next release. Thanks for pointing it out!
