### ISSUE TITLE
Options don't seem to work

### ISSUE THREAD

**Issue by joelazwar** [Niaz-Ul-Haque/nlinks#11]
I tried all the options with the syntax "nlinks -v, nlinks --v, nlinks --version, etc." And none of them seem to work, they've just defaulted as a file and just result in an error that says "no such file or directory"

Could you test it on your computer?

**Comment by Niaz-Ul-Haque** [comment]
Wait a sec, what? I will try it out and let you know. Thank you for pointing this crucial info out.

**Comment by Niaz-Ul-Haque** [comment]
Ok, it tried it out. But, it seemed to be working fine. Is possible for you to check it again? Thanks for bringing up this issue. I wan tt o know if it is just working for me or not. 
![1](https://user-images.githubusercontent.com/48073912/94288780-d162b000-ff25-11ea-9aa7-52b87afadfa3.PNG)
![2](https://user-images.githubusercontent.com/48073912/94288791-d58ecd80-ff25-11ea-89fa-d23f9033722e.PNG)

**Comment by joelazwar** [comment]
sure no problem, i suspected it might be a problem on my end thats why i asked to check. ill test it out some more and let you know

**Comment by joelazwar** [comment]
my bad it was just a problem on my end, I think it had something to do with installing an older version of the program globally (maybe that version had that problem) but I reinstalled the latest branch and its working as intended
