### ISSUE TITLE
No arguments should indicate how to use the help option as well

### ISSUE THREAD

**Issue by joelazwar** [Niaz-Ul-Haque/nlinks#12]
In addition to how to use your CLI, the empty argument statement maybe should also indicate the h option for more info on the other options.

Just a suggestion, I think the prof mentioned it in the release 0.1 requirements as well

> "running the tool with no arguments should print a standard help/usage message showing how to run the tool, which command line arguments can be passed, etc."

[https://github.com/Seneca-CDOT/topics-in-open-source-2020/wiki/release-0.1](url)

**Comment by Niaz-Ul-Haque** [comment]
Oh I see, I thought he only meant version and the name. Thank you! I implement it right away
