### ISSUE TITLE
Lab 4 Adding ignore file.

### ISSUE THREAD

**Issue by ghost** [Niaz-Ul-Haque/nlinks#16]
Hello, @Niaz-Ul-Haque I noticed your program does not have to ignore specific URLs. Can I implement an ignore functionality.?

**Comment by Niaz-Ul-Haque** [comment]
It's all you, my friend!

**Comment by ghost** [comment]
everything has been tested and pushed to your repository can you please confirm everything is working on your machine?

**Comment by Niaz-Ul-Haque** [comment]
will do, thanks.

**Comment by ghost** [comment]
please check my repository [here](https://github.com/jiyoungsin/nlinks.git).
