### ISSUE TITLE
Move require packages to top

### ISSUE THREAD

**Issue by c3ho** [Niaz-Ul-Haque/nlinks#2]
https://github.com/Niaz-Ul-Haque/nlinks/blob/adff79502af6a717ba978ebd69f09b5a06447cda/src/cli.js#L27-L28

There are other requires at the top of the page, these should be moved to where the rest of the `require` are

**Comment by Niaz-Ul-Haque** [comment]
Ayt, a rookie mistake from me. should have checked my code a few more times rather I got excited and pushed it. Thanks for pointing it out.
