### ISSUE TITLE
Test files extension does not match with their content

### ISSUE THREAD

**Issue by sanji11** [Niaz-Ul-Haque/nlinks#5]
The test file extension does not match with the content. For ex, urls.html has the content of .txt file where index.txt has content of html file. Though it’s not a big issue, I just want to point it out maybe you misplaced it.

**Comment by Niaz-Ul-Haque** [comment]
Ohh I see what you mean. that was me trying out with different types of extensions. The contents are the same because I copy-pasted them to see if its working or not. Thank you for pointing it out, should have made it more clear.
