### ISSUE TITLE
update for --version option

### ISSUE THREAD

**Issue by sanji11** [Niaz-Ul-Haque/nlinks#6]
When you are checking if args[2] == "--version”, you can also print the tool name as the prof suggested on the optional features sections.
 
![image](https://user-images.githubusercontent.com/64912621/93954017-a35d5000-fd1a-11ea-884c-3c24f8fd44ae.png)

**Comment by Niaz-Ul-Haque** [comment]
Ohh I forgot to add this one. I add it soon, thanks for pointing it out!

**Comment by Niaz-Ul-Haque** [comment]
Done. thanks again!
