### ISSUE TITLE
Suggestion about --file option

### ISSUE THREAD

**Issue by sanji11** [Niaz-Ul-Haque/nlinks#7]
When you check if `args[2] == "--files" `and prints a message to inform additional features will be added in future, it seems unnecessary to make a separate option only for that purpose. You can just add that following message at the end of the help message. Normally, the `--files` `--f `option is used with a value which is filename.

**Comment by Niaz-Ul-Haque** [comment]
I see I'll do that on the next release. Thank you for pointing it out!
