### ISSUE TITLE
cli gets stuck at the very end

### ISSUE THREAD

**Issue by sanji11** [Niaz-Ul-Haque/nlinks#8]
When I run your cli, it can not process all the links you provided in the file. It got stuck at the very end. 
For ex, in your urls.html file you have 828 links, but it can process 818 links. Also, at the end, it gets slower.

![image](https://user-images.githubusercontent.com/64912621/93954503-e23fd580-fd1b-11ea-93d0-eeda9cd1b8fc.png)
![image](https://user-images.githubusercontent.com/64912621/93954515-e8ce4d00-fd1b-11ea-83e0-f75fbf47173a.png)

I am not sure why it is. Is it something to do with using async function?

**Comment by Niaz-Ul-Haque** [comment]
Ohhh, my program is designed like that. The library that I am using tends to become slower at the end of every file. But, I can assure you it works. Thanks.
